/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProviderType = IDL.Variant({
  'AWS' : IDL.Null,
  'GCP' : IDL.Null,
  'Azure' : IDL.Null,
});
export const PlaybookResult = IDL.Record({
  'rawApiError' : IDL.Opt(IDL.Text),
  'dryRunPreview' : IDL.Opt(IDL.Text),
  'provider' : IDL.Opt(ProviderType),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ComplianceFramework = IDL.Variant({
  'CISAws' : IDL.Null,
  'CISGCP' : IDL.Null,
  'SOC2' : IDL.Null,
  'ISO27001' : IDL.Null,
  'CISAzure' : IDL.Null,
  'NISTCSF' : IDL.Null,
});
export const Result = IDL.Variant({
  'ok' : IDL.Record({ 'csvData' : IDL.Text, 'reportId' : IDL.Text }),
  'err' : IDL.Text,
});
export const AlertStatus = IDL.Variant({
  'Open' : IDL.Null,
  'InProgress' : IDL.Null,
  'Resolved' : IDL.Null,
});
export const MitreTag = IDL.Record({
  'techniqueId' : IDL.Text,
  'technique' : IDL.Text,
  'tactic' : IDL.Text,
});
export const Severity = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
  'Unknown' : IDL.Null,
});
export const DomainRep = IDL.Record({
  'suspiciousVotes' : IDL.Nat,
  'maliciousVotes' : IDL.Nat,
  'cleanVotes' : IDL.Nat,
  'lastAnalysisDate' : IDL.Text,
});
export const IpReputation = IDL.Record({
  'isp' : IDL.Text,
  'country' : IDL.Text,
  'lastReported' : IDL.Text,
  'totalReports' : IDL.Nat,
  'abuseScore' : IDL.Nat,
});
export const MitreDetail = IDL.Record({
  'techniqueName' : IDL.Text,
  'tacticName' : IDL.Text,
  'mitigations' : IDL.Text,
  'description' : IDL.Text,
});
export const AlertEnrichment = IDL.Record({
  'domainRep' : IDL.Opt(DomainRep),
  'knownMaliciousIp' : IDL.Bool,
  'ipReputation' : IDL.Opt(IpReputation),
  'enrichedAt' : IDL.Opt(IDL.Text),
  'mitreDetail' : IDL.Opt(MitreDetail),
});
export const NormalizedAlert = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Opt(IDL.Text),
  'status' : AlertStatus,
  'mitre' : IDL.Opt(MitreTag),
  'title' : IDL.Text,
  'findingId' : IDL.Text,
  'provider' : ProviderType,
  'accountId' : IDL.Opt(IDL.Text),
  'customer' : IDL.Text,
  'assetId' : IDL.Opt(IDL.Text),
  'owner' : IDL.Opt(IDL.Text),
  'rawFindingId' : IDL.Text,
  'recurrenceCount' : IDL.Nat,
  'description' : IDL.Text,
  'ingestionSource' : IDL.Opt(
    IDL.Variant({ 'Poll' : IDL.Null, 'Webhook' : IDL.Null })
  ),
  'originalSeverity' : IDL.Text,
  'timestamp' : IDL.Int,
  'assetType' : IDL.Opt(IDL.Text),
  'severity' : Severity,
  'enrichment' : IDL.Opt(AlertEnrichment),
});
export const RuleSeverityThreshold = IDL.Variant({
  'All' : IDL.Null,
  'AnyHigh' : IDL.Null,
  'CriticalOrHigh' : IDL.Null,
  'AnyCritical' : IDL.Null,
  'AnyLow' : IDL.Null,
  'AnyMedium' : IDL.Null,
});
export const NotificationChannel = IDL.Variant({
  'Email' : IDL.Null,
  'InApp' : IDL.Null,
  'TeamsWebhook' : IDL.Null,
});
export const AlertRule = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Opt(IDL.Text),
  'escalationRecipient' : IDL.Opt(IDL.Text),
  'severityThreshold' : IDL.Opt(RuleSeverityThreshold),
  'provider' : IDL.Opt(ProviderType),
  'customer' : IDL.Text,
  'assetId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'escalationMinutes' : IDL.Opt(IDL.Nat),
  'channels' : IDL.Vec(NotificationChannel),
  'cooldownMinutes' : IDL.Nat,
  'enabled' : IDL.Bool,
  'findingType' : IDL.Opt(IDL.Text),
});
export const AssetType = IDL.Variant({
  'S3' : IDL.Null,
  'AzureVM' : IDL.Null,
  'EC2' : IDL.Null,
  'RDS' : IDL.Null,
  'AzureDatabase' : IDL.Null,
  'GCPStorage' : IDL.Null,
  'GCPCloudSQL' : IDL.Null,
  'Lambda' : IDL.Null,
  'AzureStorage' : IDL.Null,
  'GCPCompute' : IDL.Null,
  'Other' : IDL.Null,
});
export const Asset = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'provider' : ProviderType,
  'accountId' : IDL.Text,
  'customer' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'assetType' : AssetType,
  'lastSeen' : IDL.Int,
  'riskScore' : IDL.Nat,
  'openFindings' : IDL.Nat,
});
export const AuditLogEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'customer' : IDL.Text,
  'actorId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const ControlStatus = IDL.Variant({
  'Passing' : IDL.Null,
  'NoCoverage' : IDL.Null,
  'Failing' : IDL.Null,
});
export const ComplianceControl = IDL.Record({
  'status' : ControlStatus,
  'title' : IDL.Text,
  'provider' : IDL.Opt(ProviderType),
  'framework' : ComplianceFramework,
  'failingFindings' : IDL.Nat,
  'description' : IDL.Text,
  'controlId' : IDL.Text,
  'remediationGuidance' : IDL.Text,
  'passingFindings' : IDL.Nat,
});
export const ComplianceTrendEntry = IDL.Record({
  'passingControls' : IDL.Nat,
  'framework' : ComplianceFramework,
  'totalControls' : IDL.Nat,
  'score' : IDL.Nat,
  'weekTimestamp' : IDL.Int,
});
export const IncidentStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Investigating' : IDL.Null,
  'Resolved' : IDL.Null,
});
export const CorrelatedIncident = IDL.Record({
  'status' : IncidentStatus,
  'incidentId' : IDL.Text,
  'customer' : IDL.Text,
  'sourceAlerts' : IDL.Vec(IDL.Text),
  'detectedAt' : IDL.Int,
  'assignedOwner' : IDL.Opt(IDL.Text),
  'sourceIp' : IDL.Opt(IDL.Text),
  'sourceProviders' : IDL.Vec(ProviderType),
  'timeDeltaMinutes' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'affectedResources' : IDL.Vec(IDL.Text),
  'severity' : Severity,
  'correlationWindowMinutes' : IDL.Nat,
  'incidentType' : IDL.Text,
});
export const CorrelationStats = IDL.Record({
  'totalAllTime' : IDL.Nat,
  'byType' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalToday' : IDL.Nat,
  'totalThisWeek' : IDL.Nat,
});
export const CredentialHealth = IDL.Variant({
  'Error' : IDL.Text,
  'Authenticating' : IDL.Null,
  'Valid' : IDL.Null,
  'ExpiringSoon' : IDL.Text,
  'Expired' : IDL.Null,
});
export const CredentialHealthStatus = IDL.Record({
  'provider' : IDL.Text,
  'expiryNs' : IDL.Opt(IDL.Int),
  'health' : CredentialHealth,
});
export const PollingStatus = IDL.Variant({
  'Error' : IDL.Null,
  'AuthPaused' : IDL.Null,
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const PollingInterval = IDL.Variant({
  'OneHour' : IDL.Null,
  'ThirtyMin' : IDL.Null,
  'FifteenMin' : IDL.Null,
  'FiveMin' : IDL.Null,
});
export const ProviderPollingState = IDL.Record({
  'status' : PollingStatus,
  'provider' : ProviderType,
  'interval' : PollingInterval,
  'lastPollAttempt' : IDL.Opt(IDL.Int),
  'lastSuccessfulPoll' : IDL.Opt(IDL.Int),
  'findingsToday' : IDL.Nat,
  'lastError' : IDL.Opt(IDL.Text),
  'consecutiveFailures' : IDL.Nat,
});
export const IngestionStats = IDL.Record({
  'providerStates' : IDL.Vec(ProviderPollingState),
  'activeProviders' : IDL.Nat,
  'totalFindingsToday' : IDL.Nat,
});
export const NotificationStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Sent' : IDL.Null,
  'Acknowledged' : IDL.Null,
});
export const NotificationLog = IDL.Record({
  'id' : IDL.Text,
  'status' : NotificationStatus,
  'acknowledgedAt' : IDL.Opt(IDL.Int),
  'customer' : IDL.Text,
  'ruleId' : IDL.Text,
  'recipient' : IDL.Text,
  'alertId' : IDL.Text,
  'acknowledged' : IDL.Bool,
  'timestamp' : IDL.Int,
  'channel' : NotificationChannel,
});
export const RawFinding = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'findingId' : IDL.Text,
  'provider' : ProviderType,
  'accountId' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'rawMetadata' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : Severity,
});
export const GeneratedReport = IDL.Record({
  'csvData' : IDL.Opt(IDL.Text),
  'customer' : IDL.Text,
  'providerScope' : IDL.Vec(IDL.Text),
  'generatedAt' : IDL.Text,
  'generatedBy' : IDL.Text,
  'dateRangeStart' : IDL.Text,
  'dateRangeEnd' : IDL.Text,
  'reportType' : IDL.Text,
  'reportId' : IDL.Text,
  'format' : IDL.Text,
});
export const TimelineEvent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'provider' : IDL.Opt(ProviderType),
  'customer' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : IDL.Opt(Severity),
  'eventType' : IDL.Text,
});
export const SearchResult = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'provider' : IDL.Opt(ProviderType),
  'customer' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'sourceModule' : IDL.Text,
  'severity' : IDL.Opt(Severity),
});
export const AwsCredentials = IDL.Record({
  'externalId' : IDL.Opt(IDL.Text),
  'roleArn' : IDL.Text,
  'regions' : IDL.Vec(IDL.Text),
});
export const AzureCredentials = IDL.Record({
  'clientId' : IDL.Text,
  'subscriptionIds' : IDL.Vec(IDL.Text),
  'tenantId' : IDL.Text,
  'clientSecret' : IDL.Text,
});
export const GcpCredentials = IDL.Record({
  'serviceAccountJson' : IDL.Text,
  'projectIds' : IDL.Vec(IDL.Text),
});
export const ConnectionTestResult = IDL.Variant({
  'Success' : IDL.Text,
  'Failure' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'acknowledgeNotification' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'blockIp' : IDL.Func(
      [
        IDL.Record({
          'ip' : IDL.Text,
          'customer' : IDL.Text,
          'providers' : IDL.Vec(ProviderType),
          'dryRun' : IDL.Bool,
        }),
      ],
      [PlaybookResult],
      [],
    ),
  'deleteAlertRule' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteReport' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'disableAzureAdAccount' : IDL.Func(
      [
        IDL.Record({
          'customer' : IDL.Text,
          'userPrincipalName' : IDL.Text,
          'dryRun' : IDL.Bool,
        }),
      ],
      [PlaybookResult],
      [],
    ),
  'enrichAlertPublic' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'escalateToIncident' : IDL.Func(
      [
        IDL.Record({
          'customer' : IDL.Text,
          'assignedOwner' : IDL.Opt(IDL.Text),
          'alertId' : IDL.Text,
          'notes' : IDL.Opt(IDL.Text),
          'severity' : IDL.Text,
          'dryRun' : IDL.Bool,
        }),
      ],
      [PlaybookResult],
      [],
    ),
  'exportComplianceCsv' : IDL.Func(
      [ComplianceFramework],
      [IDL.Text],
      ['query'],
    ),
  'exportCompliancePdf' : IDL.Func(
      [ComplianceFramework],
      [IDL.Vec(IDL.Nat8)],
      ['query'],
    ),
  'forceGcpIamReview' : IDL.Func(
      [
        IDL.Record({
          'customer' : IDL.Text,
          'projectId' : IDL.Text,
          'dryRun' : IDL.Bool,
        }),
      ],
      [PlaybookResult],
      [],
    ),
  'generateReport' : IDL.Func(
      [
        IDL.Record({
          'customer' : IDL.Text,
          'providerScope' : IDL.Vec(IDL.Text),
          'dateRangeStart' : IDL.Text,
          'dateRangeEnd' : IDL.Text,
          'reportType' : IDL.Text,
        }),
      ],
      [Result],
      [],
    ),
  'getAlertById' : IDL.Func([IDL.Text], [IDL.Opt(NormalizedAlert)], ['query']),
  'getAlertRules' : IDL.Func([IDL.Text], [IDL.Vec(AlertRule)], ['query']),
  'getAlertsForCorrelation' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(NormalizedAlert)],
      ['query'],
    ),
  'getAssetById' : IDL.Func([IDL.Text], [IDL.Opt(Asset)], ['query']),
  'getAssetFindings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NormalizedAlert)],
      ['query'],
    ),
  'getAssets' : IDL.Func(
      [
        IDL.Record({
          'region' : IDL.Opt(IDL.Text),
          'minRiskScore' : IDL.Opt(IDL.Nat),
          'provider' : IDL.Opt(ProviderType),
          'customer' : IDL.Text,
          'limit' : IDL.Nat,
          'assetType' : IDL.Opt(AssetType),
        }),
      ],
      [IDL.Vec(Asset)],
      ['query'],
    ),
  'getAuditLog' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(AuditLogEntry)],
      ['query'],
    ),
  'getComplianceControlGaps' : IDL.Func(
      [ComplianceFramework],
      [IDL.Vec(ComplianceControl)],
      ['query'],
    ),
  'getComplianceStatus' : IDL.Func(
      [ComplianceFramework, IDL.Opt(ProviderType)],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'failing' : IDL.Nat,
          'controls' : IDL.Vec(ComplianceControl),
          'score' : IDL.Nat,
          'passing' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getComplianceTrend' : IDL.Func(
      [ComplianceFramework],
      [IDL.Vec(ComplianceTrendEntry)],
      ['query'],
    ),
  'getCorrelatedIncidentById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CorrelatedIncident)],
      ['query'],
    ),
  'getCorrelatedIncidents' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, CorrelatedIncident))],
      ['query'],
    ),
  'getCorrelationStats' : IDL.Func([], [CorrelationStats], ['query']),
  'getCredentialHealth' : IDL.Func(
      [],
      [IDL.Vec(CredentialHealthStatus)],
      ['query'],
    ),
  'getEnrichmentKeys' : IDL.Func(
      [],
      [
        IDL.Record({
          'abuseIpdbKeySet' : IDL.Bool,
          'virusTotalKeySet' : IDL.Bool,
        }),
      ],
      [],
    ),
  'getFailedIngestions' : IDL.Func(
      [IDL.Opt(ProviderType), IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Text,
            'status' : IDL.Text,
            'provider' : IDL.Text,
            'errorMessage' : IDL.Text,
            'errorType' : IDL.Text,
            'timestamp' : IDL.Int,
            'rawPayload' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getIngestionStats' : IDL.Func([], [IngestionStats], ['query']),
  'getNormalizedAlerts' : IDL.Func(
      [
        IDL.Record({
          'status' : IDL.Opt(AlertStatus),
          'provider' : IDL.Opt(ProviderType),
          'customer' : IDL.Text,
          'limit' : IDL.Nat,
          'severity' : IDL.Opt(Severity),
        }),
      ],
      [IDL.Vec(NormalizedAlert)],
      ['query'],
    ),
  'getNotificationLogs' : IDL.Func(
      [IDL.Record({ 'customer' : IDL.Text, 'limit' : IDL.Nat })],
      [IDL.Vec(NotificationLog)],
      ['query'],
    ),
  'getPipelineHealth' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'provider' : IDL.Text,
            'failedIngestionCount' : IDL.Nat,
            'pollEventsToday' : IDL.Nat,
            'normalizationSuccessRate' : IDL.Float64,
            'webhookEventsToday' : IDL.Nat,
            'avgLatencyMs' : IDL.Float64,
          })
        ),
      ],
      ['query'],
    ),
  'getProviderStates' : IDL.Func(
      [],
      [IDL.Vec(ProviderPollingState)],
      ['query'],
    ),
  'getRawFindings' : IDL.Func(
      [ProviderType, IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'hasMore' : IDL.Bool,
          'totalCount' : IDL.Nat,
          'items' : IDL.Vec(RawFinding),
        }),
      ],
      ['query'],
    ),
  'getReportCsv' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getReportEmailConfig' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'reportType' : IDL.Text,
            'recipients' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      [],
    ),
  'getReports' : IDL.Func([IDL.Text], [IDL.Vec(GeneratedReport)], []),
  'getTimeline' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(TimelineEvent)],
      ['query'],
    ),
  'getWebhookStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'webhookNormalizationRate' : IDL.Float64,
          'webhookEventsToday' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'globalSearch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Record({ 'hasMore' : IDL.Bool, 'results' : IDL.Vec(SearchResult) })],
      ['query'],
    ),
  'hasAdminCredentials' : IDL.Func([], [IDL.Bool], ['query']),
  'http_request' : IDL.Func(
      [
        IDL.Record({
          'url' : IDL.Text,
          'method' : IDL.Text,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        }),
      ],
      [
        IDL.Record({
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          'upgrade' : IDL.Opt(IDL.Bool),
          'streaming_strategy' : IDL.Opt(IDL.Null),
          'status_code' : IDL.Nat16,
        }),
      ],
      ['query'],
    ),
  'http_request_update' : IDL.Func(
      [
        IDL.Record({
          'url' : IDL.Text,
          'method' : IDL.Text,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        }),
      ],
      [
        IDL.Record({
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          'upgrade' : IDL.Opt(IDL.Bool),
          'streaming_strategy' : IDL.Opt(IDL.Null),
          'status_code' : IDL.Nat16,
        }),
      ],
      [],
    ),
  'isolateResource' : IDL.Func(
      [
        IDL.Record({
          'provider' : ProviderType,
          'customer' : IDL.Text,
          'resourceId' : IDL.Text,
          'dryRun' : IDL.Bool,
        }),
      ],
      [PlaybookResult],
      [],
    ),
  'revokeIamCredentials' : IDL.Func(
      [
        IDL.Record({
          'provider' : ProviderType,
          'customer' : IDL.Text,
          'userId' : IDL.Text,
          'accessKeyId' : IDL.Opt(IDL.Text),
          'dryRun' : IDL.Bool,
        }),
      ],
      [PlaybookResult],
      [],
    ),
  'saveAlertRule' : IDL.Func([AlertRule], [IDL.Bool], []),
  'saveAwsCredentials' : IDL.Func([AwsCredentials], [], []),
  'saveAzureCredentials' : IDL.Func([AzureCredentials], [], []),
  'saveEnrichmentKeys' : IDL.Func(
      [
        IDL.Record({
          'virusTotalKey' : IDL.Opt(IDL.Text),
          'abuseIpdbKey' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
      [],
    ),
  'saveGcpCredentials' : IDL.Func([GcpCredentials], [], []),
  'saveReportEmailConfig' : IDL.Func(
      [
        IDL.Record({
          'customer' : IDL.Text,
          'reportType' : IDL.Text,
          'recipients' : IDL.Vec(IDL.Text),
        }),
      ],
      [],
      [],
    ),
  'seedMockAlertsAndRunCorrelation' : IDL.Func(
      [],
      [IDL.Vec(CorrelatedIncident)],
      [],
    ),
  'setPollingInterval' : IDL.Func([ProviderType, PollingInterval], [], []),
  'testAwsConnection' : IDL.Func([], [ConnectionTestResult], []),
  'testAzureConnection' : IDL.Func([], [ConnectionTestResult], []),
  'testGcpConnection' : IDL.Func([], [ConnectionTestResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerPoll' : IDL.Func([ProviderType], [], []),
  'updateAlertStatus' : IDL.Func(
      [IDL.Text, AlertStatus, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateCorrelatedIncidentStatus' : IDL.Func(
      [IDL.Text, IncidentStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProviderType = IDL.Variant({
    'AWS' : IDL.Null,
    'GCP' : IDL.Null,
    'Azure' : IDL.Null,
  });
  const PlaybookResult = IDL.Record({
    'rawApiError' : IDL.Opt(IDL.Text),
    'dryRunPreview' : IDL.Opt(IDL.Text),
    'provider' : IDL.Opt(ProviderType),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ComplianceFramework = IDL.Variant({
    'CISAws' : IDL.Null,
    'CISGCP' : IDL.Null,
    'SOC2' : IDL.Null,
    'ISO27001' : IDL.Null,
    'CISAzure' : IDL.Null,
    'NISTCSF' : IDL.Null,
  });
  const Result = IDL.Variant({
    'ok' : IDL.Record({ 'csvData' : IDL.Text, 'reportId' : IDL.Text }),
    'err' : IDL.Text,
  });
  const AlertStatus = IDL.Variant({
    'Open' : IDL.Null,
    'InProgress' : IDL.Null,
    'Resolved' : IDL.Null,
  });
  const MitreTag = IDL.Record({
    'techniqueId' : IDL.Text,
    'technique' : IDL.Text,
    'tactic' : IDL.Text,
  });
  const Severity = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
    'Unknown' : IDL.Null,
  });
  const DomainRep = IDL.Record({
    'suspiciousVotes' : IDL.Nat,
    'maliciousVotes' : IDL.Nat,
    'cleanVotes' : IDL.Nat,
    'lastAnalysisDate' : IDL.Text,
  });
  const IpReputation = IDL.Record({
    'isp' : IDL.Text,
    'country' : IDL.Text,
    'lastReported' : IDL.Text,
    'totalReports' : IDL.Nat,
    'abuseScore' : IDL.Nat,
  });
  const MitreDetail = IDL.Record({
    'techniqueName' : IDL.Text,
    'tacticName' : IDL.Text,
    'mitigations' : IDL.Text,
    'description' : IDL.Text,
  });
  const AlertEnrichment = IDL.Record({
    'domainRep' : IDL.Opt(DomainRep),
    'knownMaliciousIp' : IDL.Bool,
    'ipReputation' : IDL.Opt(IpReputation),
    'enrichedAt' : IDL.Opt(IDL.Text),
    'mitreDetail' : IDL.Opt(MitreDetail),
  });
  const NormalizedAlert = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Opt(IDL.Text),
    'status' : AlertStatus,
    'mitre' : IDL.Opt(MitreTag),
    'title' : IDL.Text,
    'findingId' : IDL.Text,
    'provider' : ProviderType,
    'accountId' : IDL.Opt(IDL.Text),
    'customer' : IDL.Text,
    'assetId' : IDL.Opt(IDL.Text),
    'owner' : IDL.Opt(IDL.Text),
    'rawFindingId' : IDL.Text,
    'recurrenceCount' : IDL.Nat,
    'description' : IDL.Text,
    'ingestionSource' : IDL.Opt(
      IDL.Variant({ 'Poll' : IDL.Null, 'Webhook' : IDL.Null })
    ),
    'originalSeverity' : IDL.Text,
    'timestamp' : IDL.Int,
    'assetType' : IDL.Opt(IDL.Text),
    'severity' : Severity,
    'enrichment' : IDL.Opt(AlertEnrichment),
  });
  const RuleSeverityThreshold = IDL.Variant({
    'All' : IDL.Null,
    'AnyHigh' : IDL.Null,
    'CriticalOrHigh' : IDL.Null,
    'AnyCritical' : IDL.Null,
    'AnyLow' : IDL.Null,
    'AnyMedium' : IDL.Null,
  });
  const NotificationChannel = IDL.Variant({
    'Email' : IDL.Null,
    'InApp' : IDL.Null,
    'TeamsWebhook' : IDL.Null,
  });
  const AlertRule = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Opt(IDL.Text),
    'escalationRecipient' : IDL.Opt(IDL.Text),
    'severityThreshold' : IDL.Opt(RuleSeverityThreshold),
    'provider' : IDL.Opt(ProviderType),
    'customer' : IDL.Text,
    'assetId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'escalationMinutes' : IDL.Opt(IDL.Nat),
    'channels' : IDL.Vec(NotificationChannel),
    'cooldownMinutes' : IDL.Nat,
    'enabled' : IDL.Bool,
    'findingType' : IDL.Opt(IDL.Text),
  });
  const AssetType = IDL.Variant({
    'S3' : IDL.Null,
    'AzureVM' : IDL.Null,
    'EC2' : IDL.Null,
    'RDS' : IDL.Null,
    'AzureDatabase' : IDL.Null,
    'GCPStorage' : IDL.Null,
    'GCPCloudSQL' : IDL.Null,
    'Lambda' : IDL.Null,
    'AzureStorage' : IDL.Null,
    'GCPCompute' : IDL.Null,
    'Other' : IDL.Null,
  });
  const Asset = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'provider' : ProviderType,
    'accountId' : IDL.Text,
    'customer' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'assetType' : AssetType,
    'lastSeen' : IDL.Int,
    'riskScore' : IDL.Nat,
    'openFindings' : IDL.Nat,
  });
  const AuditLogEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'customer' : IDL.Text,
    'actorId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const ControlStatus = IDL.Variant({
    'Passing' : IDL.Null,
    'NoCoverage' : IDL.Null,
    'Failing' : IDL.Null,
  });
  const ComplianceControl = IDL.Record({
    'status' : ControlStatus,
    'title' : IDL.Text,
    'provider' : IDL.Opt(ProviderType),
    'framework' : ComplianceFramework,
    'failingFindings' : IDL.Nat,
    'description' : IDL.Text,
    'controlId' : IDL.Text,
    'remediationGuidance' : IDL.Text,
    'passingFindings' : IDL.Nat,
  });
  const ComplianceTrendEntry = IDL.Record({
    'passingControls' : IDL.Nat,
    'framework' : ComplianceFramework,
    'totalControls' : IDL.Nat,
    'score' : IDL.Nat,
    'weekTimestamp' : IDL.Int,
  });
  const IncidentStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Investigating' : IDL.Null,
    'Resolved' : IDL.Null,
  });
  const CorrelatedIncident = IDL.Record({
    'status' : IncidentStatus,
    'incidentId' : IDL.Text,
    'customer' : IDL.Text,
    'sourceAlerts' : IDL.Vec(IDL.Text),
    'detectedAt' : IDL.Int,
    'assignedOwner' : IDL.Opt(IDL.Text),
    'sourceIp' : IDL.Opt(IDL.Text),
    'sourceProviders' : IDL.Vec(ProviderType),
    'timeDeltaMinutes' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'affectedResources' : IDL.Vec(IDL.Text),
    'severity' : Severity,
    'correlationWindowMinutes' : IDL.Nat,
    'incidentType' : IDL.Text,
  });
  const CorrelationStats = IDL.Record({
    'totalAllTime' : IDL.Nat,
    'byType' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalToday' : IDL.Nat,
    'totalThisWeek' : IDL.Nat,
  });
  const CredentialHealth = IDL.Variant({
    'Error' : IDL.Text,
    'Authenticating' : IDL.Null,
    'Valid' : IDL.Null,
    'ExpiringSoon' : IDL.Text,
    'Expired' : IDL.Null,
  });
  const CredentialHealthStatus = IDL.Record({
    'provider' : IDL.Text,
    'expiryNs' : IDL.Opt(IDL.Int),
    'health' : CredentialHealth,
  });
  const PollingStatus = IDL.Variant({
    'Error' : IDL.Null,
    'AuthPaused' : IDL.Null,
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const PollingInterval = IDL.Variant({
    'OneHour' : IDL.Null,
    'ThirtyMin' : IDL.Null,
    'FifteenMin' : IDL.Null,
    'FiveMin' : IDL.Null,
  });
  const ProviderPollingState = IDL.Record({
    'status' : PollingStatus,
    'provider' : ProviderType,
    'interval' : PollingInterval,
    'lastPollAttempt' : IDL.Opt(IDL.Int),
    'lastSuccessfulPoll' : IDL.Opt(IDL.Int),
    'findingsToday' : IDL.Nat,
    'lastError' : IDL.Opt(IDL.Text),
    'consecutiveFailures' : IDL.Nat,
  });
  const IngestionStats = IDL.Record({
    'providerStates' : IDL.Vec(ProviderPollingState),
    'activeProviders' : IDL.Nat,
    'totalFindingsToday' : IDL.Nat,
  });
  const NotificationStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Sent' : IDL.Null,
    'Acknowledged' : IDL.Null,
  });
  const NotificationLog = IDL.Record({
    'id' : IDL.Text,
    'status' : NotificationStatus,
    'acknowledgedAt' : IDL.Opt(IDL.Int),
    'customer' : IDL.Text,
    'ruleId' : IDL.Text,
    'recipient' : IDL.Text,
    'alertId' : IDL.Text,
    'acknowledged' : IDL.Bool,
    'timestamp' : IDL.Int,
    'channel' : NotificationChannel,
  });
  const RawFinding = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'findingId' : IDL.Text,
    'provider' : ProviderType,
    'accountId' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'rawMetadata' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : Severity,
  });
  const GeneratedReport = IDL.Record({
    'csvData' : IDL.Opt(IDL.Text),
    'customer' : IDL.Text,
    'providerScope' : IDL.Vec(IDL.Text),
    'generatedAt' : IDL.Text,
    'generatedBy' : IDL.Text,
    'dateRangeStart' : IDL.Text,
    'dateRangeEnd' : IDL.Text,
    'reportType' : IDL.Text,
    'reportId' : IDL.Text,
    'format' : IDL.Text,
  });
  const TimelineEvent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'provider' : IDL.Opt(ProviderType),
    'customer' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : IDL.Opt(Severity),
    'eventType' : IDL.Text,
  });
  const SearchResult = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'provider' : IDL.Opt(ProviderType),
    'customer' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'sourceModule' : IDL.Text,
    'severity' : IDL.Opt(Severity),
  });
  const AwsCredentials = IDL.Record({
    'externalId' : IDL.Opt(IDL.Text),
    'roleArn' : IDL.Text,
    'regions' : IDL.Vec(IDL.Text),
  });
  const AzureCredentials = IDL.Record({
    'clientId' : IDL.Text,
    'subscriptionIds' : IDL.Vec(IDL.Text),
    'tenantId' : IDL.Text,
    'clientSecret' : IDL.Text,
  });
  const GcpCredentials = IDL.Record({
    'serviceAccountJson' : IDL.Text,
    'projectIds' : IDL.Vec(IDL.Text),
  });
  const ConnectionTestResult = IDL.Variant({
    'Success' : IDL.Text,
    'Failure' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'acknowledgeNotification' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'blockIp' : IDL.Func(
        [
          IDL.Record({
            'ip' : IDL.Text,
            'customer' : IDL.Text,
            'providers' : IDL.Vec(ProviderType),
            'dryRun' : IDL.Bool,
          }),
        ],
        [PlaybookResult],
        [],
      ),
    'deleteAlertRule' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteReport' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'disableAzureAdAccount' : IDL.Func(
        [
          IDL.Record({
            'customer' : IDL.Text,
            'userPrincipalName' : IDL.Text,
            'dryRun' : IDL.Bool,
          }),
        ],
        [PlaybookResult],
        [],
      ),
    'enrichAlertPublic' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'escalateToIncident' : IDL.Func(
        [
          IDL.Record({
            'customer' : IDL.Text,
            'assignedOwner' : IDL.Opt(IDL.Text),
            'alertId' : IDL.Text,
            'notes' : IDL.Opt(IDL.Text),
            'severity' : IDL.Text,
            'dryRun' : IDL.Bool,
          }),
        ],
        [PlaybookResult],
        [],
      ),
    'exportComplianceCsv' : IDL.Func(
        [ComplianceFramework],
        [IDL.Text],
        ['query'],
      ),
    'exportCompliancePdf' : IDL.Func(
        [ComplianceFramework],
        [IDL.Vec(IDL.Nat8)],
        ['query'],
      ),
    'forceGcpIamReview' : IDL.Func(
        [
          IDL.Record({
            'customer' : IDL.Text,
            'projectId' : IDL.Text,
            'dryRun' : IDL.Bool,
          }),
        ],
        [PlaybookResult],
        [],
      ),
    'generateReport' : IDL.Func(
        [
          IDL.Record({
            'customer' : IDL.Text,
            'providerScope' : IDL.Vec(IDL.Text),
            'dateRangeStart' : IDL.Text,
            'dateRangeEnd' : IDL.Text,
            'reportType' : IDL.Text,
          }),
        ],
        [Result],
        [],
      ),
    'getAlertById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(NormalizedAlert)],
        ['query'],
      ),
    'getAlertRules' : IDL.Func([IDL.Text], [IDL.Vec(AlertRule)], ['query']),
    'getAlertsForCorrelation' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(NormalizedAlert)],
        ['query'],
      ),
    'getAssetById' : IDL.Func([IDL.Text], [IDL.Opt(Asset)], ['query']),
    'getAssetFindings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NormalizedAlert)],
        ['query'],
      ),
    'getAssets' : IDL.Func(
        [
          IDL.Record({
            'region' : IDL.Opt(IDL.Text),
            'minRiskScore' : IDL.Opt(IDL.Nat),
            'provider' : IDL.Opt(ProviderType),
            'customer' : IDL.Text,
            'limit' : IDL.Nat,
            'assetType' : IDL.Opt(AssetType),
          }),
        ],
        [IDL.Vec(Asset)],
        ['query'],
      ),
    'getAuditLog' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(AuditLogEntry)],
        ['query'],
      ),
    'getComplianceControlGaps' : IDL.Func(
        [ComplianceFramework],
        [IDL.Vec(ComplianceControl)],
        ['query'],
      ),
    'getComplianceStatus' : IDL.Func(
        [ComplianceFramework, IDL.Opt(ProviderType)],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'failing' : IDL.Nat,
            'controls' : IDL.Vec(ComplianceControl),
            'score' : IDL.Nat,
            'passing' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getComplianceTrend' : IDL.Func(
        [ComplianceFramework],
        [IDL.Vec(ComplianceTrendEntry)],
        ['query'],
      ),
    'getCorrelatedIncidentById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CorrelatedIncident)],
        ['query'],
      ),
    'getCorrelatedIncidents' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, CorrelatedIncident))],
        ['query'],
      ),
    'getCorrelationStats' : IDL.Func([], [CorrelationStats], ['query']),
    'getCredentialHealth' : IDL.Func(
        [],
        [IDL.Vec(CredentialHealthStatus)],
        ['query'],
      ),
    'getEnrichmentKeys' : IDL.Func(
        [],
        [
          IDL.Record({
            'abuseIpdbKeySet' : IDL.Bool,
            'virusTotalKeySet' : IDL.Bool,
          }),
        ],
        [],
      ),
    'getFailedIngestions' : IDL.Func(
        [IDL.Opt(ProviderType), IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Text,
              'status' : IDL.Text,
              'provider' : IDL.Text,
              'errorMessage' : IDL.Text,
              'errorType' : IDL.Text,
              'timestamp' : IDL.Int,
              'rawPayload' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getIngestionStats' : IDL.Func([], [IngestionStats], ['query']),
    'getNormalizedAlerts' : IDL.Func(
        [
          IDL.Record({
            'status' : IDL.Opt(AlertStatus),
            'provider' : IDL.Opt(ProviderType),
            'customer' : IDL.Text,
            'limit' : IDL.Nat,
            'severity' : IDL.Opt(Severity),
          }),
        ],
        [IDL.Vec(NormalizedAlert)],
        ['query'],
      ),
    'getNotificationLogs' : IDL.Func(
        [IDL.Record({ 'customer' : IDL.Text, 'limit' : IDL.Nat })],
        [IDL.Vec(NotificationLog)],
        ['query'],
      ),
    'getPipelineHealth' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'provider' : IDL.Text,
              'failedIngestionCount' : IDL.Nat,
              'pollEventsToday' : IDL.Nat,
              'normalizationSuccessRate' : IDL.Float64,
              'webhookEventsToday' : IDL.Nat,
              'avgLatencyMs' : IDL.Float64,
            })
          ),
        ],
        ['query'],
      ),
    'getProviderStates' : IDL.Func(
        [],
        [IDL.Vec(ProviderPollingState)],
        ['query'],
      ),
    'getRawFindings' : IDL.Func(
        [ProviderType, IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'hasMore' : IDL.Bool,
            'totalCount' : IDL.Nat,
            'items' : IDL.Vec(RawFinding),
          }),
        ],
        ['query'],
      ),
    'getReportCsv' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getReportEmailConfig' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'reportType' : IDL.Text,
              'recipients' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        [],
      ),
    'getReports' : IDL.Func([IDL.Text], [IDL.Vec(GeneratedReport)], []),
    'getTimeline' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(TimelineEvent)],
        ['query'],
      ),
    'getWebhookStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'webhookNormalizationRate' : IDL.Float64,
            'webhookEventsToday' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'globalSearch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [
          IDL.Record({
            'hasMore' : IDL.Bool,
            'results' : IDL.Vec(SearchResult),
          }),
        ],
        ['query'],
      ),
    'hasAdminCredentials' : IDL.Func([], [IDL.Bool], ['query']),
    'http_request' : IDL.Func(
        [
          IDL.Record({
            'url' : IDL.Text,
            'method' : IDL.Text,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          }),
        ],
        [
          IDL.Record({
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
            'upgrade' : IDL.Opt(IDL.Bool),
            'streaming_strategy' : IDL.Opt(IDL.Null),
            'status_code' : IDL.Nat16,
          }),
        ],
        ['query'],
      ),
    'http_request_update' : IDL.Func(
        [
          IDL.Record({
            'url' : IDL.Text,
            'method' : IDL.Text,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          }),
        ],
        [
          IDL.Record({
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
            'upgrade' : IDL.Opt(IDL.Bool),
            'streaming_strategy' : IDL.Opt(IDL.Null),
            'status_code' : IDL.Nat16,
          }),
        ],
        [],
      ),
    'isolateResource' : IDL.Func(
        [
          IDL.Record({
            'provider' : ProviderType,
            'customer' : IDL.Text,
            'resourceId' : IDL.Text,
            'dryRun' : IDL.Bool,
          }),
        ],
        [PlaybookResult],
        [],
      ),
    'revokeIamCredentials' : IDL.Func(
        [
          IDL.Record({
            'provider' : ProviderType,
            'customer' : IDL.Text,
            'userId' : IDL.Text,
            'accessKeyId' : IDL.Opt(IDL.Text),
            'dryRun' : IDL.Bool,
          }),
        ],
        [PlaybookResult],
        [],
      ),
    'saveAlertRule' : IDL.Func([AlertRule], [IDL.Bool], []),
    'saveAwsCredentials' : IDL.Func([AwsCredentials], [], []),
    'saveAzureCredentials' : IDL.Func([AzureCredentials], [], []),
    'saveEnrichmentKeys' : IDL.Func(
        [
          IDL.Record({
            'virusTotalKey' : IDL.Opt(IDL.Text),
            'abuseIpdbKey' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
        [],
      ),
    'saveGcpCredentials' : IDL.Func([GcpCredentials], [], []),
    'saveReportEmailConfig' : IDL.Func(
        [
          IDL.Record({
            'customer' : IDL.Text,
            'reportType' : IDL.Text,
            'recipients' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
        [],
      ),
    'seedMockAlertsAndRunCorrelation' : IDL.Func(
        [],
        [IDL.Vec(CorrelatedIncident)],
        [],
      ),
    'setPollingInterval' : IDL.Func([ProviderType, PollingInterval], [], []),
    'testAwsConnection' : IDL.Func([], [ConnectionTestResult], []),
    'testAzureConnection' : IDL.Func([], [ConnectionTestResult], []),
    'testGcpConnection' : IDL.Func([], [ConnectionTestResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerPoll' : IDL.Func([ProviderType], [], []),
    'updateAlertStatus' : IDL.Func(
        [IDL.Text, AlertStatus, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateCorrelatedIncidentStatus' : IDL.Func(
        [IDL.Text, IncidentStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };