/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertEnrichment {
  'domainRep' : [] | [DomainRep],
  'knownMaliciousIp' : boolean,
  'ipReputation' : [] | [IpReputation],
  'enrichedAt' : [] | [string],
  'mitreDetail' : [] | [MitreDetail],
}
export interface AlertRule {
  'id' : string,
  'region' : [] | [string],
  'escalationRecipient' : [] | [string],
  'severityThreshold' : [] | [RuleSeverityThreshold],
  'provider' : [] | [ProviderType],
  'customer' : string,
  'assetId' : [] | [string],
  'name' : string,
  'escalationMinutes' : [] | [bigint],
  'channels' : Array<NotificationChannel>,
  'cooldownMinutes' : bigint,
  'enabled' : boolean,
  'findingType' : [] | [string],
}
export type AlertStatus = { 'Open' : null } |
  { 'InProgress' : null } |
  { 'Resolved' : null };
export interface Asset {
  'id' : string,
  'region' : string,
  'provider' : ProviderType,
  'accountId' : string,
  'customer' : string,
  'name' : string,
  'tags' : Array<[string, string]>,
  'assetType' : AssetType,
  'lastSeen' : bigint,
  'riskScore' : bigint,
  'openFindings' : bigint,
}
export type AssetType = { 'S3' : null } |
  { 'AzureVM' : null } |
  { 'EC2' : null } |
  { 'RDS' : null } |
  { 'AzureDatabase' : null } |
  { 'GCPStorage' : null } |
  { 'GCPCloudSQL' : null } |
  { 'Lambda' : null } |
  { 'AzureStorage' : null } |
  { 'GCPCompute' : null } |
  { 'Other' : null };
export interface AuditLogEntry {
  'id' : string,
  'action' : string,
  'customer' : string,
  'actorId' : string,
  'timestamp' : bigint,
  'details' : string,
}
export interface AwsCredentials {
  'externalId' : [] | [string],
  'roleArn' : string,
  'regions' : Array<string>,
}
export interface AzureCredentials {
  'clientId' : string,
  'subscriptionIds' : Array<string>,
  'tenantId' : string,
  'clientSecret' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ComplianceControl {
  'status' : ControlStatus,
  'title' : string,
  'provider' : [] | [ProviderType],
  'framework' : ComplianceFramework,
  'failingFindings' : bigint,
  'description' : string,
  'controlId' : string,
  'remediationGuidance' : string,
  'passingFindings' : bigint,
}
export type ComplianceFramework = { 'CISAws' : null } |
  { 'CISGCP' : null } |
  { 'SOC2' : null } |
  { 'ISO27001' : null } |
  { 'CISAzure' : null } |
  { 'NISTCSF' : null };
export interface ComplianceTrendEntry {
  'passingControls' : bigint,
  'framework' : ComplianceFramework,
  'totalControls' : bigint,
  'score' : bigint,
  'weekTimestamp' : bigint,
}
export type ConnectionTestResult = { 'Success' : string } |
  { 'Failure' : string };
export type ControlStatus = { 'Passing' : null } |
  { 'NoCoverage' : null } |
  { 'Failing' : null };
export interface CorrelatedIncident {
  'status' : IncidentStatus,
  'incidentId' : string,
  'customer' : string,
  'sourceAlerts' : Array<string>,
  'detectedAt' : bigint,
  'assignedOwner' : [] | [string],
  'sourceIp' : [] | [string],
  'sourceProviders' : Array<ProviderType>,
  'timeDeltaMinutes' : number,
  'notes' : [] | [string],
  'affectedResources' : Array<string>,
  'severity' : Severity,
  'correlationWindowMinutes' : bigint,
  'incidentType' : string,
}
export interface CorrelationStats {
  'totalAllTime' : bigint,
  'byType' : Array<[string, bigint]>,
  'totalToday' : bigint,
  'totalThisWeek' : bigint,
}
export type CredentialHealth = { 'Error' : string } |
  { 'Authenticating' : null } |
  { 'Valid' : null } |
  { 'ExpiringSoon' : string } |
  { 'Expired' : null };
export interface CredentialHealthStatus {
  'provider' : string,
  'expiryNs' : [] | [bigint],
  'health' : CredentialHealth,
}
export interface DomainRep {
  'suspiciousVotes' : bigint,
  'maliciousVotes' : bigint,
  'cleanVotes' : bigint,
  'lastAnalysisDate' : string,
}
export interface GcpCredentials {
  'serviceAccountJson' : string,
  'projectIds' : Array<string>,
}
export interface GeneratedReport {
  'csvData' : [] | [string],
  'customer' : string,
  'providerScope' : Array<string>,
  'generatedAt' : string,
  'generatedBy' : string,
  'dateRangeStart' : string,
  'dateRangeEnd' : string,
  'reportType' : string,
  'reportId' : string,
  'format' : string,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type IncidentStatus = { 'Open' : null } |
  { 'Investigating' : null } |
  { 'Resolved' : null };
export interface IngestionStats {
  'providerStates' : Array<ProviderPollingState>,
  'activeProviders' : bigint,
  'totalFindingsToday' : bigint,
}
export interface IpReputation {
  'isp' : string,
  'country' : string,
  'lastReported' : string,
  'totalReports' : bigint,
  'abuseScore' : bigint,
}
export interface MitreDetail {
  'techniqueName' : string,
  'tacticName' : string,
  'mitigations' : string,
  'description' : string,
}
export interface MitreTag {
  'techniqueId' : string,
  'technique' : string,
  'tactic' : string,
}
export interface NormalizedAlert {
  'id' : string,
  'region' : [] | [string],
  'status' : AlertStatus,
  'mitre' : [] | [MitreTag],
  'title' : string,
  'findingId' : string,
  'provider' : ProviderType,
  'accountId' : [] | [string],
  'customer' : string,
  'assetId' : [] | [string],
  'owner' : [] | [string],
  'rawFindingId' : string,
  'recurrenceCount' : bigint,
  'description' : string,
  'ingestionSource' : [] | [{ 'Poll' : null } | { 'Webhook' : null }],
  'originalSeverity' : string,
  'timestamp' : bigint,
  'assetType' : [] | [string],
  'severity' : Severity,
  'enrichment' : [] | [AlertEnrichment],
}
export type NotificationChannel = { 'Email' : null } |
  { 'InApp' : null } |
  { 'TeamsWebhook' : null };
export interface NotificationLog {
  'id' : string,
  'status' : NotificationStatus,
  'acknowledgedAt' : [] | [bigint],
  'customer' : string,
  'ruleId' : string,
  'recipient' : string,
  'alertId' : string,
  'acknowledged' : boolean,
  'timestamp' : bigint,
  'channel' : NotificationChannel,
}
export type NotificationStatus = { 'Failed' : null } |
  { 'Sent' : null } |
  { 'Acknowledged' : null };
export interface PlaybookResult {
  'rawApiError' : [] | [string],
  'dryRunPreview' : [] | [string],
  'provider' : [] | [ProviderType],
  'message' : string,
  'success' : boolean,
}
export type PollingInterval = { 'OneHour' : null } |
  { 'ThirtyMin' : null } |
  { 'FifteenMin' : null } |
  { 'FiveMin' : null };
export type PollingStatus = { 'Error' : null } |
  { 'AuthPaused' : null } |
  { 'Inactive' : null } |
  { 'Active' : null };
export interface ProviderPollingState {
  'status' : PollingStatus,
  'provider' : ProviderType,
  'interval' : PollingInterval,
  'lastPollAttempt' : [] | [bigint],
  'lastSuccessfulPoll' : [] | [bigint],
  'findingsToday' : bigint,
  'lastError' : [] | [string],
  'consecutiveFailures' : bigint,
}
export type ProviderType = { 'AWS' : null } |
  { 'GCP' : null } |
  { 'Azure' : null };
export interface RawFinding {
  'id' : string,
  'region' : [] | [string],
  'title' : string,
  'findingId' : string,
  'provider' : ProviderType,
  'accountId' : [] | [string],
  'description' : string,
  'rawMetadata' : string,
  'timestamp' : bigint,
  'severity' : Severity,
}
export type Result = { 'ok' : { 'csvData' : string, 'reportId' : string } } |
  { 'err' : string };
export type Result_1 = { 'ok' : string } |
  { 'err' : string };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type RuleSeverityThreshold = { 'All' : null } |
  { 'AnyHigh' : null } |
  { 'CriticalOrHigh' : null } |
  { 'AnyCritical' : null } |
  { 'AnyLow' : null } |
  { 'AnyMedium' : null };
export interface SearchResult {
  'id' : string,
  'title' : string,
  'provider' : [] | [ProviderType],
  'customer' : string,
  'description' : string,
  'timestamp' : bigint,
  'sourceModule' : string,
  'severity' : [] | [Severity],
}
export type Severity = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null } |
  { 'Unknown' : null };
export interface TimelineEvent {
  'id' : string,
  'title' : string,
  'provider' : [] | [ProviderType],
  'customer' : string,
  'description' : string,
  'timestamp' : bigint,
  'severity' : [] | [Severity],
  'eventType' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface UserAssignmentView {
  'principal' : string,
  'providers' : Array<ProviderType>,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  /**
   * / Acknowledge a notification log entry.
   */
  'acknowledgeNotification' : ActorMethod<[string], boolean>,
  /**
   * / Admin: assign (replace) the full set of providers a principal may access.
   * / Composes with the existing requireAuth guard (rejects anonymous callers).
   * / ProviderType is a closed variant, so every element is a known provider.
   */
  'assignProviderAccess' : ActorMethod<
    [Principal, Array<ProviderType>],
    undefined
  >,
  /**
   * / Block an IP address across one or more cloud providers.
   * / dryRun=true returns a preview without making any API calls.
   */
  'blockIp' : ActorMethod<
    [
      {
        'ip' : string,
        'customer' : string,
        'providers' : Array<ProviderType>,
        'dryRun' : boolean,
      },
    ],
    PlaybookResult
  >,
  /**
   * / Delete an alert rule by ID.
   */
  'deleteAlertRule' : ActorMethod<[string], boolean>,
  /**
   * / Delete a generated report by ID.
   */
  'deleteReport' : ActorMethod<[string, string], undefined>,
  /**
   * / Disable an Azure AD user account via Microsoft Graph API.
   */
  'disableAzureAdAccount' : ActorMethod<
    [{ 'customer' : string, 'userPrincipalName' : string, 'dryRun' : boolean }],
    PlaybookResult
  >,
  /**
   * / Trigger enrichment for a specific alert on demand.
   */
  'enrichAlertPublic' : ActorMethod<[string, string], Result_1>,
  /**
   * / Escalate an alert to a full correlated incident and create a Halo ticket.
   */
  'escalateToIncident' : ActorMethod<
    [
      {
        'customer' : string,
        'assignedOwner' : [] | [string],
        'alertId' : string,
        'notes' : [] | [string],
        'severity' : string,
        'dryRun' : boolean,
      },
    ],
    PlaybookResult
  >,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Export compliance report as CSV text.
   */
  'exportComplianceCsv' : ActorMethod<[ComplianceFramework], string>,
  /**
   * / Export compliance report as PDF blob.
   */
  'exportCompliancePdf' : ActorMethod<[ComplianceFramework], Uint8Array>,
  /**
   * / Force a GCP IAM review for a project, flagging over-privileged bindings.
   */
  'forceGcpIamReview' : ActorMethod<
    [{ 'customer' : string, 'projectId' : string, 'dryRun' : boolean }],
    PlaybookResult
  >,
  /**
   * / Generate a report as CSV and store it.
   */
  'generateReport' : ActorMethod<
    [
      {
        'customer' : string,
        'providerScope' : Array<string>,
        'dateRangeStart' : string,
        'dateRangeEnd' : string,
        'reportType' : string,
      },
    ],
    Result
  >,
  /**
   * / Find a single alert by its ID.
   * / Requires the caller to be assigned to the alert's provider.
   */
  'getAlertById' : ActorMethod<[string], [] | [NormalizedAlert]>,
  /**
   * / Return all alert rules for a given customer.
   */
  'getAlertRules' : ActorMethod<[string], Array<AlertRule>>,
  /**
   * / Return normalized alerts whose id matches any entry in alertIds.
   * / Scoped to the providers the caller is assigned to.
   */
  'getAlertsForCorrelation' : ActorMethod<
    [Array<string>],
    Array<NormalizedAlert>
  >,
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Find a single asset by its ID.
   * / Requires the caller to be assigned to the asset's provider.
   */
  'getAssetById' : ActorMethod<[string], [] | [Asset]>,
  /**
   * / Return all open/in-progress normalized alerts for a given asset.
   * / Scoped to the providers the caller is assigned to.
   */
  'getAssetFindings' : ActorMethod<[string], Array<NormalizedAlert>>,
  /**
   * / Return assets matching the provided filter criteria.
   * / Scoped to the providers the caller is assigned to.
   */
  'getAssets' : ActorMethod<
    [
      {
        'region' : [] | [string],
        'minRiskScore' : [] | [bigint],
        'provider' : [] | [ProviderType],
        'customer' : string,
        'limit' : bigint,
        'assetType' : [] | [AssetType],
      },
    ],
    Array<Asset>
  >,
  /**
   * / Return audit log entries for a customer, sorted by timestamp descending.
   */
  'getAuditLog' : ActorMethod<[string, bigint], Array<AuditLogEntry>>,
  /**
   * / Return controls that have status Failing or NoCoverage.
   */
  'getComplianceControlGaps' : ActorMethod<
    [ComplianceFramework],
    Array<ComplianceControl>
  >,
  /**
   * / Return compliance status for a framework, counting passing/failing findings per control.
   * / Scoped to the providers the caller is assigned to.
   */
  'getComplianceStatus' : ActorMethod<
    [ComplianceFramework, [] | [ProviderType]],
    {
      'total' : bigint,
      'failing' : bigint,
      'controls' : Array<ComplianceControl>,
      'score' : bigint,
      'passing' : bigint,
    }
  >,
  /**
   * / Return compliance trend entries for a framework sorted by weekTimestamp ascending.
   */
  'getComplianceTrend' : ActorMethod<
    [ComplianceFramework],
    Array<ComplianceTrendEntry>
  >,
  /**
   * / Return a correlated incident by its incidentId, or null if not found.
   * / Requires the caller to be assigned to one of the incident's source providers.
   */
  'getCorrelatedIncidentById' : ActorMethod<
    [string],
    [] | [CorrelatedIncident]
  >,
  /**
   * / Return the most recent `limit` correlated incidents sorted by detectedAt descending.
   * / Scoped to incidents touching providers the caller is assigned to.
   */
  'getCorrelatedIncidents' : ActorMethod<
    [bigint],
    Array<[string, CorrelatedIncident]>
  >,
  /**
   * / Return aggregated correlation statistics for the dashboard panel.
   * / Scoped to incidents touching providers the caller is assigned to.
   */
  'getCorrelationStats' : ActorMethod<[], CorrelationStats>,
  /**
   * / Return the health status of each provider's credentials.
   * / Checks in-memory token cache expiry; no network call.
   * / Scoped to the providers the caller is assigned to.
   */
  'getCredentialHealth' : ActorMethod<[], Array<CredentialHealthStatus>>,
  /**
   * / Return which enrichment keys are configured (booleans only — never the key values).
   */
  'getEnrichmentKeys' : ActorMethod<
    [],
    { 'abuseIpdbKeySet' : boolean, 'virusTotalKeySet' : boolean }
  >,
  /**
   * / Return failed ingestion records, optionally filtered by provider.
   * / provider field is returned as Text to avoid Candid variant decoding issues on the frontend.
   * / Scoped to the providers the caller is assigned to.
   */
  'getFailedIngestions' : ActorMethod<
    [[] | [ProviderType], bigint],
    Array<
      {
        'id' : string,
        'status' : string,
        'provider' : string,
        'errorMessage' : string,
        'errorType' : string,
        'timestamp' : bigint,
        'rawPayload' : string,
      }
    >
  >,
  /**
   * / Return aggregated ingestion statistics for the dashboard.
   * / Scoped to the providers the caller is assigned to.
   */
  'getIngestionStats' : ActorMethod<[], IngestionStats>,
  /**
   * / Frontend: read the current caller's assigned providers.
   */
  'getMyProviders' : ActorMethod<[], Array<ProviderType>>,
  /**
   * / Return normalized alerts matching the provided filter criteria.
   * / Scoped to the providers the caller is assigned to.
   */
  'getNormalizedAlerts' : ActorMethod<
    [
      {
        'status' : [] | [AlertStatus],
        'provider' : [] | [ProviderType],
        'customer' : string,
        'limit' : bigint,
        'severity' : [] | [Severity],
      },
    ],
    Array<NormalizedAlert>
  >,
  /**
   * / Return notification logs for a customer, sorted by timestamp descending.
   */
  'getNotificationLogs' : ActorMethod<
    [{ 'customer' : string, 'limit' : bigint }],
    Array<NotificationLog>
  >,
  /**
   * / Return per-provider pipeline health stats for the dashboard.
   * / provider field is returned as Text to avoid Candid variant decoding issues on the frontend.
   * / Scoped to the providers the caller is assigned to.
   */
  'getPipelineHealth' : ActorMethod<
    [],
    Array<
      {
        'provider' : string,
        'failedIngestionCount' : bigint,
        'pollEventsToday' : bigint,
        'normalizationSuccessRate' : number,
        'webhookEventsToday' : bigint,
        'avgLatencyMs' : number,
      }
    >
  >,
  /**
   * / Return per-provider polling state (status, last poll time, error info).
   * / Scoped to the providers the caller is assigned to.
   */
  'getProviderStates' : ActorMethod<[], Array<ProviderPollingState>>,
  /**
   * / Return paginated raw findings for a given provider.
   * / limit: max items to return (default 100, max 500). offset: starting index.
   * / Requires the caller to be assigned to the requested provider.
   */
  'getRawFindings' : ActorMethod<
    [ProviderType, bigint, bigint],
    { 'hasMore' : boolean, 'totalCount' : bigint, 'items' : Array<RawFinding> }
  >,
  /**
   * / Return the CSV data for a specific report.
   */
  'getReportCsv' : ActorMethod<[string, string], [] | [string]>,
  /**
   * / Return email configs for a customer.
   */
  'getReportEmailConfig' : ActorMethod<
    [string],
    Array<{ 'reportType' : string, 'recipients' : Array<string> }>
  >,
  /**
   * / Return the list of generated reports for a customer (without CSV data).
   */
  'getReports' : ActorMethod<[string], Array<GeneratedReport>>,
  /**
   * / Return recent timeline events for a customer, sorted by timestamp descending.
   * / Scoped to the providers the caller is assigned to.
   */
  'getTimeline' : ActorMethod<[string, bigint], Array<TimelineEvent>>,
  /**
   * / Return which providers have a webhook secret configured (booleans only —
   * / never the secret values).
   */
  'getWebhookSecretStatus' : ActorMethod<
    [],
    { 'azureSet' : boolean, 'gcpSet' : boolean, 'awsSet' : boolean }
  >,
  /**
   * / Return aggregated webhook statistics for the dashboard.
   * / Scoped to the providers the caller is assigned to.
   */
  'getWebhookStats' : ActorMethod<
    [],
    { 'webhookNormalizationRate' : number, 'webhookEventsToday' : bigint }
  >,
  /**
   * / Search across alerts, assets, and audit log.
   * / maxResults: cap total results (default 100, max 500). hasMore indicates truncation.
   * / Scoped to the providers the caller is assigned to.
   */
  'globalSearch' : ActorMethod<
    [string, string, bigint],
    { 'hasMore' : boolean, 'results' : Array<SearchResult> }
  >,
  /**
   * / Returns true if credentials have been saved for at least one provider.
   */
  'hasAdminCredentials' : ActorMethod<[], boolean>,
  'http_request' : ActorMethod<
    [
      {
        'url' : string,
        'method' : string,
        'body' : Uint8Array,
        'headers' : Array<[string, string]>,
      },
    ],
    {
      'body' : Uint8Array,
      'headers' : Array<[string, string]>,
      'upgrade' : [] | [boolean],
      'streaming_strategy' : [] | [null],
      'status_code' : number,
    }
  >,
  'http_request_update' : ActorMethod<
    [
      {
        'url' : string,
        'method' : string,
        'body' : Uint8Array,
        'headers' : Array<[string, string]>,
      },
    ],
    {
      'body' : Uint8Array,
      'headers' : Array<[string, string]>,
      'upgrade' : [] | [boolean],
      'streaming_strategy' : [] | [null],
      'status_code' : number,
    }
  >,
  /**
   * / Isolate a resource by modifying its network configuration.
   */
  'isolateResource' : ActorMethod<
    [
      {
        'provider' : ProviderType,
        'customer' : string,
        'resourceId' : string,
        'dryRun' : boolean,
      },
    ],
    PlaybookResult
  >,
  /**
   * / Admin: list all users and their provider assignments.
   */
  'listUserAssignments' : ActorMethod<[], Array<UserAssignmentView>>,
  /**
   * / Admin: remove a single provider from a principal's access.
   */
  'removeProviderAccess' : ActorMethod<[Principal, ProviderType], undefined>,
  /**
   * / Revoke IAM credentials for a user/service account across providers.
   */
  'revokeIamCredentials' : ActorMethod<
    [
      {
        'provider' : ProviderType,
        'customer' : string,
        'userId' : string,
        'accessKeyId' : [] | [string],
        'dryRun' : boolean,
      },
    ],
    PlaybookResult
  >,
  /**
   * / Insert or update an alert rule.
   */
  'saveAlertRule' : ActorMethod<[AlertRule], boolean>,
  /**
   * / Store AWS credentials (role ARN + optional external ID + regions) in the canister.
   */
  'saveAwsCredentials' : ActorMethod<[AwsCredentials], undefined>,
  /**
   * / Store Azure credentials (client ID/secret/tenant + subscriptions) in the canister.
   */
  'saveAzureCredentials' : ActorMethod<[AzureCredentials], undefined>,
  /**
   * / Save enrichment API keys (AbuseIPDB and VirusTotal).
   * / Key values are never returned to the frontend.
   */
  'saveEnrichmentKeys' : ActorMethod<
    [{ 'virusTotalKey' : [] | [string], 'abuseIpdbKey' : [] | [string] }],
    undefined
  >,
  /**
   * / Store GCP credentials (service account JSON + project IDs) in the canister.
   */
  'saveGcpCredentials' : ActorMethod<[GcpCredentials], undefined>,
  /**
   * / Save (upsert) a report email configuration.
   */
  'saveReportEmailConfig' : ActorMethod<
    [
      {
        'customer' : string,
        'reportType' : string,
        'recipients' : Array<string>,
      },
    ],
    undefined
  >,
  /**
   * / Save the webhook signature secret for a provider.
   * / The secret value is stored write-only and is never returned to the frontend.
   */
  'saveWebhookSecret' : ActorMethod<[ProviderType, string], undefined>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Seed 4 mock normalized alerts (idempotent) and run the correlation engine.
   * / Returns the newly detected correlated incidents. Gated behind auth.
   */
  'seedMockAlertsAndRunCorrelation' : ActorMethod<
    [],
    Array<CorrelatedIncident>
  >,
  /**
   * / Update the polling interval for a specific provider.
   */
  'setPollingInterval' : ActorMethod<
    [ProviderType, PollingInterval],
    undefined
  >,
  /**
   * / Validate stored AWS credentials against the live API.
   */
  'testAwsConnection' : ActorMethod<[], ConnectionTestResult>,
  /**
   * / Validate stored Azure credentials against the live API.
   */
  'testAzureConnection' : ActorMethod<[], ConnectionTestResult>,
  /**
   * / Validate stored GCP credentials against the live API.
   */
  'testGcpConnection' : ActorMethod<[], ConnectionTestResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  /**
   * / Trigger an immediate poll for the specified provider.
   */
  'triggerPoll' : ActorMethod<[ProviderType], undefined>,
  /**
   * / Update the status and optional owner of an alert.
   */
  'updateAlertStatus' : ActorMethod<
    [string, AlertStatus, [] | [string]],
    boolean
  >,
  /**
   * / Update status, owner, and/or notes on a correlated incident. Returns true if found.
   */
  'updateCorrelatedIncidentStatus' : ActorMethod<
    [string, IncidentStatus, [] | [string], [] | [string]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];